
azure:
  activedirectory:
    tenant-id: ${AD_TENANT_ID}
    active-directory-groups: HR

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: bob
    password: ${DATABASE_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AD_CLIENT_ID}
            client-secret: ${AD_CLIENT_SECRET}

